packages:
    - .
    - docs

minimumReleaseAge: 2880
minimumReleaseAgeExclude:
    - '@humanspeak/*'
allowBuilds:
    '@humanspeak/docs-kit': true
    esbuild: true
    sharp: true
    workerd: true
    '@humanspeak/docs-kit@https://codeload.github.com/humanspeak/docs-kit/tar.gz/19ef35386a88cb07c735cc11c26916eb67aab415': true
