/* This file is generated by docs-kit demoManifestPlugin({ split: true }). */

import type { DemoManifestEntry } from '@humanspeak/docs-kit'

export type DemoCodeLoader = () => Promise<{ default: DemoManifestEntry }>

export const demoCodeLoaders = {
    'editable-table/demos/Default.svelte': () =>
        import('virtual:docs-kit/demo/editable-table/demos/Default.svelte'),
    'editable-table/demos/EditableCell.svelte': () =>
        import('virtual:docs-kit/demo/editable-table/demos/EditableCell.svelte'),
    'kitchen-sink/demos/Default.svelte': () =>
        import('virtual:docs-kit/demo/kitchen-sink/demos/Default.svelte'),
    'virtual-scroll/demos/Default.svelte': () =>
        import('virtual:docs-kit/demo/virtual-scroll/demos/Default.svelte')
} satisfies Record<string, DemoCodeLoader>

export type DemoCodeLoaderKey = keyof typeof demoCodeLoaders

export const demoCodeDependencies: Partial<Record<DemoCodeLoaderKey, DemoCodeLoaderKey[]>> = {
    'editable-table/demos/Default.svelte': ['editable-table/demos/EditableCell.svelte']
}

export interface DemoCodeSample {
    /** Stable identifier rendered in the code reference header. */
    id: string
    /** Human-readable sample label rendered next to the identifier. */
    label: string
    /** Lazy loader for the pre-highlighted demo source module. */
    load: () => Promise<{ default: DemoManifestEntry }>
    /** Optional override for docs-kit's idle preload behavior. */
    preload?: 'idle' | false
}

/**
 * Builds a lazy `CodeReferenceV2` sample from docs-kit's generated demo source key.
 *
 * @param key - Demo path emitted by `demoManifestPlugin({ split: true })`.
 * @param id - Stable sample identifier rendered in the code panel.
 * @param label - Human-readable file label rendered in the code panel.
 * @param preload - Optional override for docs-kit's idle preload behavior.
 * @returns A lazy code sample compatible with docs-kit's `CodeReferenceV2`.
 */
export function demoCodeSample(
    key: DemoCodeLoaderKey,
    id: string,
    label: string,
    preload?: 'idle' | false
): DemoCodeSample {
    const sample: DemoCodeSample = {
        id,
        label,
        load: demoCodeLoaders[key]
    }

    if (preload !== undefined) {
        sample.preload = preload
    }

    return sample
}

function demoCodeLabelForKey(key: DemoCodeLoaderKey): string {
    return key.split('/').pop() ?? key
}

function demoCodeIdForKey(baseId: string, key: DemoCodeLoaderKey, index: number): string {
    if (index === 0) return baseId
    const fileName = demoCodeLabelForKey(key).replace(/\.svelte$/, '')
    const slug = fileName
        .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
        .replace(/[^a-zA-Z0-9]+/g, '-')
        .replace(/^-|-$/g, '')
        .toLowerCase()
    return `${baseId}-${slug || index}`
}

/**
 * Builds lazy `CodeReferenceV2` samples for a demo entrypoint and every
 * co-located `.svelte` component imported by that demo.
 *
 * @param key - Demo path emitted by `demoManifestPlugin({ split: true })`.
 * @param id - Stable sample identifier for the demo entrypoint.
 * @param label - Human-readable file label for the demo entrypoint.
 * @param preload - Optional override for docs-kit's idle preload behavior.
 * @returns Lazy code samples for the demo followed by local component dependencies.
 */
export function demoCodeSamples(
    key: DemoCodeLoaderKey,
    id: string,
    label: string,
    preload?: 'idle' | false
): DemoCodeSample[] {
    const keys = [key, ...(demoCodeDependencies[key] ?? [])]
    return keys.map((sampleKey, index) =>
        demoCodeSample(
            sampleKey,
            demoCodeIdForKey(id, sampleKey, index),
            index === 0 ? label : demoCodeLabelForKey(sampleKey),
            preload
        )
    )
}
